/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Core branding colors
        "on-primary-fixed": "#04006d",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed-variant": "#373a9b",
        "primary-fixed": "#e1e0ff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "primary": "#15157d",
        "error-red": "#DD3333",
        "surface-container": "#edeeef",
        "inverse-primary": "#c0c1ff",
        "on-primary-container": "#9da1ff",
        "surface-variant": "#e1e3e4",
        "on-error-container": "#93000a",
        "on-surface": "#191c1d",
        "secondary": "#a04100",
        "on-secondary-container": "#572000",
        "tertiary-container": "#004742",
        "vibrant-orange": "#FF6B00",
        "ink-black": "#1A1A1A",
        "deep-navy": "#2E3192",
        "surface-container-highest": "#e1e3e4",
        "on-background": "#191c1d",
        "outline-variant": "#c7c5d4",
        "secondary-container": "#fe6b00",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed-variant": "#00504b",
        "tertiary-fixed": "#76f7eb",
        "on-tertiary-container": "#2fbdb2",
        "primary-container": "#2e3192",
        "on-surface-variant": "#464652",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed-variant": "#7a3000",
        "secondary-fixed": "#ffdbcc",
        "on-secondary-fixed": "#351000",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "tertiary": "#002f2b",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9fa",
        "primary-fixed-dim": "#c0c1ff",
        "outline": "#777683",
        "tertiary-fixed-dim": "#56dacf",
        "surface": "#f8f9fa",
        "on-tertiary-fixed": "#00201e",
        "paper-white": "#FFFFFF",
        "background": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "surface-tint": "#4f54b4",
        "secondary-fixed-dim": "#ffb693",
        // Keep existing theme colors just in case
        originalPrimary: {
          50: '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          505: '#8b5cf6',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        dark: {
          50: '#f8fafc',
          100: '#f1f5f9',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        }
      },
      spacing: {
        "base": "8px",
        "container-max": "1200px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "label-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        sans: ['Hanken Grotesk', 'Outfit', 'Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}

